- name: check if NewRelic chart inside newrelic namespace already
  when: inventory_hostname == groups[cp_group][0]
  kubernetes.core.helm_info:
    name: newrelic-bundle
    release_namespace: newrelic
  register: newrelic_bundle_installed

- name: 
  when: inventory_hostname == groups[cp_group][0]
  debug:
    msg: "{{ newrelic_bundle_installed }}"

- name: Add NewRelic Chart Repo to helm
  when: inventory_hostname == groups[cp_group][0]
  kubernetes.core.helm_repository:
    name: newrelic
    repo_url: https://helm-charts.newrelic.com

- name: Helm Chart install NewRelic
  when: inventory_hostname == groups[cp_group][0] and newrelic_bundle_installed['status'] is not defined
  kubernetes.core.helm:
    name: newrelic-bundle
    chart_ref: newrelic/nri-bundle
    reset_values: false
    create_namespace: true
    chart_version: 5.0.88
    release_namespace: newrelic
    values: "{{ lookup('template', 'values_newrelic.yml') | from_yaml }}"

