- name: check if Calico chart installed in tigera-operator namespace already
  when: inventory_hostname == groups[cp_group][0]
  kubernetes.core.helm_info:
    name: calico
    release_namespace: tigera-operator
  register: calico_installed
  ignore_errors: true

- name: Add Calico Chart Repo to helm
  when: inventory_hostname == groups[cp_group][0]
  kubernetes.core.helm_repository:
    name: projectcalico
    repo_url: https://docs.tigera.io/calico/charts

- name: template heml calico install
  template:
    src: calico_helm_values.yaml
    dest: /tmp/calico_helm_values.yaml
  delegate_to: localhost



- name: Helm Chart install Calico CNI
  #when: inventory_hostname == groups[cp_group][0] and calico_installed['status'] is not defined
  when: inventory_hostname == groups[cp_group][0] 
  kubernetes.core.helm:
    name: calico
    chart_ref: projectcalico/tigera-operator
    reset_values: false
    create_namespace: true
    chart_version: v3.28.0
    release_namespace: tigera-operator
    values: "{{ lookup('template', 'calico_helm_values.yaml') | from_yaml }}"

- name: Wait for Calico CNI to be created in namespace calico-system
  #when: inventory_hostname == groups[cp_group][0] and calico_installed['status'] is not defined
  when: inventory_hostname == groups[cp_group][0] 
  kubernetes.core.k8s_info:
    namespace: calico-system
    kind: Pod
    wait: yes
    wait_sleep: 10
    wait_timeout: 360
  register: cni_up

