- name: check if Flannel chart installed in "{{ flannel_namespace }}" namespace already
  when: inventory_hostname == groups[cp_group][0]
  kubernetes.core.helm_info:
    name: flannel 
    release_namespace: "{{ flannel_namespace }}"
  register: flannel_installed
  ignore_errors: true

- name: Add Flannel Chart Repo to helm
  when: inventory_hostname == groups[cp_group][0]
  kubernetes.core.helm_repository:
    name: flannel
    repo_url: https://flannel-io.github.io/flannel/

#- name: template helm  install
#  template:
#    src: calico_helm_values.yaml
#    dest: /tmp/calico_helm_values.yaml
#  delegate_to: localhost

- name: Helm Chart install Flannel CNI
  when: inventory_hostname == groups[cp_group][0] 
  kubernetes.core.helm:
    name: flannel
    chart_ref: flannel/flannel
    reset_values: false
    create_namespace: false
    chart_version: v0.25.5
    release_namespace: "{{ flannel_namespace }}"
    set_values:
      - value: "podCidr={{ k8_pod_cidr_network }}"
        value_type: string

- name: Wait for flannel CNI to be created in namespace kube-flannel
  #when: inventory_hostname == groups[cp_group][0] and calico_installed['status'] is not defined
  when: inventory_hostname == groups[cp_group][0] 
  kubernetes.core.k8s_info:
    namespace: "{{ flannel_namespace }}"
    kind: Pod
    wait: yes
    wait_sleep: 10
    wait_timeout: 360
  register: cni_up

