---
- name: Apply node labels
  become: True
  shell:
    cmd: "kubectl label node {{ inventory_hostname_short }} {{ topology_label }}"
  tags:
    - k8_install
  delegate_to: "{{ groups[cp_group][0] }}"
