global:
  licenseKey: {{ newrelic_license_key }}
  cluster: {{ k8_cluster_name }}

newrelic-prometheus-agent:
# Automatically scrape prometheus metrics for annotated services in the cluster
# Collecting prometheus metrics for large clusters might impact data usage significantly
  enabled: false
nri-metadata-injection:
# Deploy our webhook to link APM and Kubernetes entities
  enabled: true
nri-kube-events:
# Report Kubernetes events
  enabled: true
newrelic-logging:
# Report logs for containers running in the cluster
  enabled: false
kube-state-metrics:
# Deploy kube-state-metrics in the cluster.
# Set this to true unless it is already deployed.
  enabled: true
