- name: Kubernetes setup profile root
  become: True
  shell:
    cmd: "{{ execute }}"
  loop:
    - whoami
    - source /etc/profile.d/bash_completion.sh
    - source <(kubectl completion bash)
    - echo "source <(kubectl completion bash)" >> ~/.bashrc
    - echo "export KUBECONFIG=/etc/kubernetes/admin.conf" >> ~/.bashrc
    - echo "alias k=kubectl"  >> ~/.bashrc
    - echo "complete -o default -F __start_kubectl k"  >> ~/.bashrc
    - mkdir -p $HOME/.kube
    - rm -rf $HOME/.kube/config
    - cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    - chown $(id -u):$(id -g) $HOME/.kube/config
  loop_control:
    loop_var: execute

- name: Kubernetes setup profile opensystems
  become: False
  shell:
    cmd: "{{ execute }}"
  loop:
    - whoami
    - source /etc/profile.d/bash_completion.sh
    - source <(kubectl completion bash)
    - echo "source <(kubectl completion bash)" >> ~/.bashrc
    - echo "alias k=kubectl"  >> ~/.bashrc
    - echo "complete -o default -F __start_kubectl k"  >> ~/.bashrc
    - mkdir -p $HOME/.kube
    - rm -rf $HOME/.kube/config
    - sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    - sudo chown $(id -u):$(id -g) $HOME/.kube/config
  loop_control:
    loop_var: execute


