#Join kubernetes cluster
- name: Other control plane nodes waiting to join cluster
  when: inventory_hostname in groups[cp_group] and inventory_hostname != groups[cp_group][0]
  wait_for:
    path: "{{ status_file }}"
    search_regex: "cni_up"
    timeout: 600
  delegate_to: localhost

- name: SetFact cp_join_code so that other control plane nodes can join the cluster
  when: inventory_hostname in groups[cp_group] and inventory_hostname != groups[cp_group][0]
  set_fact:
    join_cluster_code: '{{ lookup("file", status_file) | regex_search("kubeadm.*") | regex_replace("\t", "") | regex_replace("\\", "")  }} --apiserver-bind-port {{ k8_api_server_bind_port }}'
  delegate_to: localhost

- name: Kubernetes node joining cluster
  become: True
  become_method: sudo
  shell:
    cmd: "{{ execute }}"
  loop:
    - "{{ join_cluster_code }}"
  loop_control:
    loop_var: execute
  throttle: 1

- name: Get node info to count number of control plane nodes in cluster
  when: inventory_hostname in groups[cp_group] and inventory_hostname != groups[cp_group][0]
  kubernetes.core.k8s_info:
    kind: Node
    label_selectors:
      - node-role.kubernetes.io/control-plane
  register: cp_nodes
  delegate_to: "{{ groups[cp_group][0] }}"

- name: Confirm all control plane nodes joined cluster
  when: inventory_hostname in groups[cp_group] and inventory_hostname != groups[cp_group][0] and (cp_nodes['resources'] | length) == (groups[cp_group] | length)
  file:
    path: "{{ lock_file }}"
    state: absent
  delegate_to: localhost
