apiVersion: v1
kind: Service
metadata:
  name: {{ k8_cntr_name }}
  namespace: {{ app_namespace }} 
spec:
  ports:
  - port: {{ cntr_service_port }}
    protocol: TCP
    targetPort: {{ cntr_ps_port }}
  selector:
    app: {{ k8_cntr_name }}
  type: NodePort
status:
  loadBalancer: {}

